### ISSUE TITLE
Data Connection couldn't be found on this project. Can I get database file .mdf?

### ISSUE THREAD

**Issue by wachara-yanu** [chsakell/spa-webapi-angularjs#1]
mr. @chsakell I can't run this project because mdf file not found in data connection. Could you send me?

**Comment by chsakell** [comment]
read the [post ](http://wp.me/p3mRWu-PT)or follow the installation instructions.

**Comment by watcharayarnu** [comment]
Instruction 
3.change the connection string inside the HomeCinema.Data/App.config and HomeCinema.Web.config according to your development environment.

How to create database match to entities because i dont know database structure
