### ISSUE TITLE
Extremely Slow response in WebApi

### ISSUE THREAD

**Issue by skyline9002** [chsakell/spa-webapi-angularjs#7]
Hi Chsakell,

I noticed your Github for a while and I think your code is designed quite clear and good. I tried to use the similar structure to kick start my new project. However, I found one of my WebApi response is extremely slow and I could not dig out the reason.

What I have done as follows:

1. Add stopwatch to monitor the server response.

![image](https://user-images.githubusercontent.com/7085798/30791558-c4a0091a-a20f-11e7-8de7-85beb2e5f687.png)

When user access to the page there will be 3 ajax requests send out:

Stopwatch value from server:

Request A:  4583ms
Request B:  1098ms
Request C:  3084ms

From Browser: 

Check the request performance.

Request A: 6340 ms
Request B: 3040ms
Request C: 21520ms

Because the same logic I have another implementation in my old project, I am pretty sure is not caused by AngularJs and entity framework parts.

Do you have any idea on this?

Thanks

**Comment by chsakell** [comment]
Hi @skyline9002 , 

I believe we would have noticed such a delay on the first place but let me run an investigation.
Tell me more about the page you noticed the delay, which are the calls exactly. Did you notice the delay on the repository as it is (localhost, same data, not modified code etc..) ?

**Comment by skyline9002** [comment]
Hi Chsakell,

The page is not the page you pushed on GitHub. I just use your architecture design and the service logic (repository) is totally changed. But before that I have a knockout version and have the same logic (repository). I can make sure the slowness is not due to the sql query. And in my Knockout version the response time is slightly more than sql query time (3000+ ms).   

So do you know any tool I can profile or monitor the whole Web Api processing tunnel? I want to log down the each step of the processing and to see the slowness is caused by which step.

Thanks

Simon

**Comment by chsakell** [comment]
I am closing this issue as it's not related to the repository.
