### ISSUE TITLE
Reducing Stocks(-) button was not working

### ISSUE THREAD

**Issue by kakadshivaji70** [chsakell/spa-webapi-angularjs#8]
Hey Chsakell,
Thanks for this application and the documentation you have provided with a detailed explanation. I really like the way you have described the concepts. I got a better understanding of the concepts like IoC & Repositories.

As I was going through, I figure out that reducing Stocks(-) button was not working while adding a new movie. So, I have made a few changes(2 files) to make it work, attaching the snaps for same.    
1) add.html
![image](https://user-images.githubusercontent.com/49365231/61183738-816e3500-a662-11e9-97dd-d2ba4d4b0677.png)

2) movieAddCtrl.js
![image](https://user-images.githubusercontent.com/49365231/61183750-a1055d80-a662-11e9-9caf-d9d0077fecfe.png)

**Comment by chsakell** [comment]
Thanks @kakadshivaji70 !!

**Comment by kakadshivaji70** [comment]
Thanks for the attention @chsakell.
